name: CI & CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create GitHub Release

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Rules & Formatting (BiomeJS)
        run: pnpm run lint

      - name: Unit & Integration Tests (Vitest)
        run: pnpm run test:run

      - name: Build Bundles (Vite Library Mode)
        run: pnpm run build

      # --- DESPLIEGUE (Solo corre al hacer Push a Main) ---
      
      - name: Get Version from package.json
        if: github.event_name == 'push'
        id: pkg_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        if: github.event_name == 'push'
        id: check_tag
        run: |
          if git rev-parse "${{ steps.pkg_version.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Extract Changelog Entry
        if: github.event_name == 'push' && steps.check_tag.outputs.exists == 'false'
        id: changelog_reader
        run: |
          VERSION_ESCAPED=$(echo "${{ steps.pkg_version.outputs.VERSION }}" | sed 's/v//' | sed 's/\./\\./g')
          BODY=$(sed -n "/## \[$VERSION_ESCAPED\]/,/## \[/p" CHANGELOG.md | sed '1d;$d')
          
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.pkg_version.outputs.VERSION }}
          name: Release ${{ steps.pkg_version.outputs.VERSION }}
          body: ${{ steps.changelog_reader.outputs.BODY }}
          draft: false
          prerelease: false
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package to NPM
        if: github.event_name == 'push' && steps.check_tag.outputs.exists == 'false'
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
